title: Study and Blog
description: Self-study and blog every day
author: Your Name

# Social links (если нужно)
github_username: ganiesenov
linkedin_username: your-linkedin

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6

# Уберите эту строку:
# theme: minima